### ISSUE TITLE
"Persistent thrust stopped"... I don't have the mod installed

### ISSUE THREAD

**Issue by psychonaut25** [bld/PersistentThrust#5]
I'm in a suborbital trajectory in KSP 1.7.3 on Windows 7 Pro x64 and I was trying to use MechJeb's warp helper to warp to my maneuver node, but I'm getting the following message: "Persistent thrust stopped - vessel not facing maneuver" and it keeps preventing me from time warping.

As far as I know, I do not even have PersistentThrust installed.  I've never installed it, and I don't want it.  I want to be able to time warp even in sub-orbital trajectories.  Is there a chance that some other mod auto-installed PersistentThrust and it's buried within a subdirectory of my GameData?  I'm really at a loss, here.

**Comment by psychonaut25** [comment]
Okay now it's happening even in a non-sub-orbital trajectory... wtf is going on here

**Comment by psychonaut25** [comment]
I performed a search in my KSP folder for any folders named "PersistentThrust" using JAM Software's Ultrasearch and I found nothing.  I would be happy to upload my log files if necessary... but I'm really confused as to how to stop this from happening.  My next maneuver node is 2 years of game time away, and as such there's no way I can simply wait for that time to surpass.

**Comment by bld** [comment]
This mod installs to the "Kerbal Space Program\GameData\PersistentThrust" directory. In this directory, there is a "Plugins" subdirectory with the file "PersistentThrust.dll", which is the plugin itself. I'm not sure why it would install anywhere else, but maybe this will help track it down?

**Comment by psychonaut25** [comment]
I don't have a "PersistentThrust" directory in my GameData  :/

**Comment by bld** [comment]
Do you have KSP Interstellar Extended installed? It has a similar check, preventing timewarp during suborbital trajectories and possibly other conditions.

**Comment by psychonaut25** [comment]
I do indeed have KSP Interstellar Extended.  Never ran into this particular problem with it before, though... and the warning message specifically mentions "PersistentThrust"

**Comment by bld** [comment]
Well, I think we shared some code awhile back.

**Comment by psychonaut25** [comment]
Ok, I'll see if I can contact the Interstellar Dev to see what they have to say... thanks for the help!

**Comment by sswelm** [comment]
In the latest beta, I have fixed some problems associated with KSPIE persistent thrust. It available at https://www.curseforge.com/kerbal/ksp-mods/ksp-interstellar-extended/files

**Comment by psychonaut25** [comment]
Confirmed fixed.  Thank you, sswelm!
